/*import 'package:projeto1/model/ParkingLot.dart';

List<ParkingLot> parkLots = [
  ParkingLot(
    parkId: 1,
    name: 'Combatentes',
    isActive: true,
    maxCapacity: 25,
    occupation: 22,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 2,
    name: 'Calçada do Combro',
    isActive: true,
    maxCapacity: 99,
    occupation: 99,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 3,
    name: 'Avenida de Pádua - Olivais',
    isActive: true,
    maxCapacity: 89,
    occupation: 46,
    parkType: 'Coberto',
  ),
  ParkingLot(
      parkId: 4,
      name: 'Parque Vila Maria',
      isActive: true,
      maxCapacity: 68,
      occupation: 68,
      parkType: 'Subterrâneo'),
  ParkingLot(
    parkId: 5,
    name: 'Estrada da Luz',
    isActive: true,
    maxCapacity: 96,
    occupation: 96,
    parkType: 'Coberto',
  ),
  ParkingLot(
    parkId: 6,
    name: 'Campo Grande',
    isActive: true,
    maxCapacity: 88,
    occupation: 18,
    parkType: 'Subterrâneo',
  ),
  ParkingLot(
    parkId: 7,
    name: 'LIDL Av. Inf. D. Henrique',
    isActive: true,
    maxCapacity: 114,
    occupation: 73,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 8,
    name: 'Parque da Graça',
    isActive: true,
    maxCapacity: 38,
    occupation: 38,
    parkType: 'Subterrâneo',
  ),
  ParkingLot(
    parkId: 9,
    name: 'Mercado de Alvalade',
    isActive: true,
    maxCapacity: 93,
    occupation: 37,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 10,
    name: 'Chão do Loureiro',
    isActive: true,
    maxCapacity: 66,
    occupation: 15,
    parkType: 'Subterrâneo',
  ),
  ParkingLot(
    parkId: 11,
    name: 'Manuel Gouveia',
    isActive: true,
    maxCapacity: 90,
    occupation: 18,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 12,
    name: 'Rego',
    isActive: true,
    maxCapacity: 100,
    occupation: 32,
    parkType: 'Superficie',
  ),
  ParkingLot(
    parkId: 13,
    name: 'Avenida Lusíada',
    isActive: true,
    maxCapacity: 92,
    occupation: 69,
    parkType: 'Coberto',
  ),
];
*/